apiVersion: v1
kind: Secret
metadata:
  name: auth-service
  namespace: payment-system
  labels:
    type: database
type: Opaque
data:
  # PostgreSQL credentials (base64 encoded)
  postgres-username: cG9zdGdyZXM=          # postgres
  postgres-password: cG9zdGdyZXM=          # postgres
  # Internal API Key (как в docker-compose)
  internal-api-key: ZGV2LWludGVybmFsLWFwaS1rZXk=  # dev-internal-api-key
  # JWT (текущий ключ в base64)
  jwt-secret: mySecretKeyForJWTGenerationInAuthenticationService2025
