apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: microservices
  labels:
    type: database
type: Opaque
data:
  # PostgreSQL credentials (base64 encoded)
  postgres-username: cG9zdGdyZXM=          # postgres
  postgres-password: cG9zdGdyZXM=          # postgres
  # Internal API Key (как в docker-compose)
  internal-api-key: ZGV2LWludGVybmFsLWFwaS1rZXk=  # dev-internal-api-key
  # JWT (текущий ключ в base64)
  jwt-secret: bXlTZWNyZXRLZXlGb3JKV1RHZW5lcmF0aW9uSW5BdXRoZW50aWNhdGlvblNlcnZpY2UyMDI1  # mySecretKeyForJWTGenerationInAuthenticationService2025
