apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: microservices
type: Opaque
stringData:
  # JWT Secret (должен совпадать с authentication-service)
  JWT_SECRET: "mySecretKeyForJWTGenerationInAuthenticationService2025"
  
  # Internal API Key для вызова internal endpoints
  INTERNAL_API_KEY: "dev-internal-api-key"

