apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: microservices
data:
  # Settings for order-service
  spring.application.name: "order-service"
  server.port: "8080"

  # Профиль Spring
  spring.profiles.active: "kubernetes"


