apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: microservices
type: Opaque
data:
  # MongoDB connection string (base64 encoded)
  # mongodb://payment-mongo-service:27017/paymentdb
  mongodb-uri: bW9uZ29kYjovL3BheW1lbnQtbW9uZ28tc2VydmljZToyNzAxNy9wYXltZW50ZGI=

