apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
  namespace: microservices
type: Opaque
data:
  # PostgreSQL credentials (base64 encoded)
  # postgres / postgres
  postgres-username: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=
  
  # JWT Secret (должен совпадать с auth-service)
  # mySecretKeyForJWTGenerationInAuthenticationService2025
  jwt-secret: bXlTZWNyZXRLZXlGb3JKV1RHZW5lcmF0aW9uSW5BdXRoZW50aWNhdGlvblNlcnZpY2UyMDI1
  
  # Internal API Key для communication с authentication-service
  # dev-internal-api-key
  internal-api-key: ZGV2LWludGVybmFsLWFwaS1rZXk=

