apiVersion: v1
kind: Service
metadata:
  name: payment-mongo-service
  namespace: microservices
  labels:
    app: payment-mongo
    component: database
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app: payment-mongo

